### ISSUE TITLE
Mulig bug ved bruk av redirect-param ved login

### ISSUE THREAD

**Issue by anostoga** [nais/wonderwall#17]
Brukar redirect-param fint for login med idporten wonderwall, men det samme feilar for azure-ad. 
Når redirect er satt redirectes det til <url>/oauth2 etter login. 

<img width="407" alt="image" src="https://user-images.githubusercontent.com/4167977/157628896-f15528cd-a0be-4d06-b990-e0ba496615f6.png">

I forsøket mitt redirecta eg til ingressen direkte, det er jo unødvendig, men det funkar fint for andre wonderwalled apps så eg mistenker at det er ein bug i ww for azure. 

Funker fint uten redirect-url, da går den til ingress som forventa.

**Comment by tronghn** [comment]
Turns out that setting the `redirect` parameter equal to a complete URL (e.g. `https://google.com`) without a trailing slash results in an empty redirect URL, which means that the callback handler will redirect to its own relative path, i.e. `/oauth2`.

Fixed in cc78d2195ba8ae2ecbfec554cfbb156066238f07.
